name: Deploy to EC2
on: 
  push:
    branches:
      - serve2
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME2 }}
        key: ${{ secrets.KEY2 }}
        port: ${{ secrets.PORT2 }}
        script: |
          cd /home/ubuntu/app
          git pull origin serve2
          docker stop FinalProject
          docker rm FinalProject
          docker build -t Final-App:latest .
          docker run -d -e "CONNECTION_DB=admin:admin123@tcp(final-project.cxhaug23hp7t.ap-southeast-1.rds.amazonaws.com:3306)/db_final_project?charset=utf8&parseTime=True&loc=Local" -p 80:8080 --name FinalProject Final-App:latest